### ISSUE TITLE
Playing with Raspberry Pi

### ISSUE THREAD

**Issue by dmathieu** [dojo-toulouse/bbl#13]

**Comment by dmathieu** [comment]
Je viendrai avec mon Pi.
@shordeaux je piquerai également un écran.

**Comment by dmathieu** [comment]
Par contre, il semble que toutes les salles soient réservées ce jour la.

**Comment by shordeaux** [comment]
on a les carmes aussi c'est pour quand? la semaine prochaine?

**Comment by dmathieu** [comment]
Non, le 11 décembre.
