### ISSUE TITLE
Changer de techno, bonne ou mauvaise idée ?

### ISSUE THREAD

**Issue by demental** [dojo-toulouse/bbl#14]
Que ce soit à titre personnel ou pour un projet existant, changer de techno, est-ce une fausse bonne idée (selon les cas) ? 
Quelles sont les raisons qui motivent le changement, pourquoi ce changement peut revêtir un caractère illusoire, avez-vous des retours d'expérience ?

**Comment by dmathieu** [comment]
Par changer de techno tu veut dire réecrire intégralement un projet?

**Comment by demental** [comment]
Oui, tout ou au moins une grosse partie d'un projet,

**Comment by dmathieu** [comment]
Ok. Ta description laissait a penser que en tant que développeur, tu ne t'intéresse qu'à une seule technologie :wink:

**Comment by enguerran** [comment]
Ta description laisse à penser que tu parles d'une [récente annonce](http://webuilddesign.com/wordpress-4-3-will-be-rewritten-in-node-js/) d'un outil de Blog/CMS qui voudrait passer de PHP à javascript.

**Comment by dmathieu** [comment]
@enguerran tu n'a peut-etre pas raté la chose, mais la date de cet article est drolement importante :wink:

**Comment by enguerran** [comment]
Quand j'ai posté mon commentaire il y a 23 heures, la date de l'article était "28 avril 2015"... argh !
![screenshot from 2015-04-30 15 03 59](https://cloud.githubusercontent.com/assets/701648/7413277/7f737c8e-ef4a-11e4-9289-52934a55f829.png)

**Comment by demental** [comment]
@enguerran , rien à voir ceci dit mais ça pourrait aussi (si on fait abstraction de la date ;))

**Comment by dmathieu** [comment]
@demental ok pour faire ce sujet la semaine prochaine?

**Comment by demental** [comment]
No problem !

Le mardi 8 septembre 2015, Damien Mathieu notifications@github.com a
écrit :

**Comment by demental** [comment]
OMW
