### ISSUE TITLE
Construire son CSS selon la convention BEM

### ISSUE THREAD

**Issue by enguerran** [dojo-toulouse/bbl#15]
Un peu de technique ?

Maintenir du CSS c'est pas facile, on dirait qu'avec une bonne convention de nommage, on arrive à tout structurer.

Une introduction sur Smashing Magazine : http://www.smashingmagazine.com/2014/07/17/bem-methodology-for-small-projects/

**Comment by demental** [comment]
C'est peut être un peu trop spécifique pour les BBL, ceci dit ça m'intéresse d'en causer et de faire des retours d'expérience là dessus.. d'autres ?

**Comment by enguerran** [comment]
En passant : une introduction vraiment courte en français ici http://putaindecode.fr/posts/css/du-css-evolutif/

**Comment by dmathieu** [comment]
@enguerran es-tu toujours partant pour discuter de ce sujet? Quand serais-tu disponible?

**Comment by enguerran** [comment]
Comme dit @demental, peut être un peu trop spécifique. On peut en causer lors de la phase apéro d'un aperoweb. Et il faudrait trouver des gens qui font du BEM. J'ai perdu la main depuis 8 mois. C'est peut-être même plus la mode.

**Comment by enguerran** [comment]
Tiens d'ailleurs le prochain aperoweb c'es sur le CSS du futur avec un véritable expert : http://toulouse.aperoweb.fr/ (inscription ici https://www.eventbrite.fr/e/billets-aperoweb-toulouse-37-future-friendly-css-20841258766)

**Comment by dmathieu** [comment]
Malheureusement, tant que cela sera des lundi soir, je ne pourrai jamais venir.

**Comment by enguerran** [comment]
Les autres participants du BBL seront peut-être intéressés.
