### ISSUE TITLE
Les tests techniques lors des entretiens d'embauche

### ISSUE THREAD

**Issue by carobee** [dojo-toulouse/bbl#16]
Souvent, les recruteurs font passer aux candidats développeurs des tests techniques avant de décider si oui ou non ils iront à l'entretien suivant.
Différents tests peuvent être proposés : QCM, études de cas, réalisation de maquette, etc... et sur différents sujets : algo, java, seo, etc...

Ces tests sont-ils pertinents / intéressants / utiles ?
Quelle sorte de test peut être meilleure qu'une autre ?
Le test idéal existe-t-il ?

**Comment by demental** [comment]
:+1:

J'en passe un lundi en + (mon premier eh ouais !) je pourrai vous faire un retour !

**Comment by avernois** [comment]
du coup, ça c'est passé comment ?

**Comment by demental** [comment]
Arf je me suis foiré lamentablement, mais c'est très positif !

Je survote pour ce topic pour le prochain BBL, j'ai à dire, c'est demain 19/06 ou le 25 ?

**Comment by carobee** [comment]
C'est le 26/6, le prochain !

**Comment by dmathieu** [comment]
Je réouvre. @carobee m'a dit qu'il n'y avait personne au repas, et elle souhaite le refaire.
