### ISSUE TITLE
Migrer ses projets sur un dépôt de code monolithique

### ISSUE THREAD

**Issue by demental** [dojo-toulouse/bbl#23]
Je voudrais faire un retour d'expérience sur ce sujet, le projet sur lequel on bosse a migré tous ses sous-projets et dépendances sur un seul repo Github. Qu'est-ce que ça apporte? Quels sont les obstacles rencontrés?

**Comment by dmathieu** [comment]
Meetup event: http://www.meetup.com/fr-FR/Software-Craftsmanship-Toulouse/events/228865287/?eventId=228865287
