### ISSUE TITLE
Stop talking about "bugs"

### ISSUE THREAD

**Issue by avernois** [dojo-toulouse/bbl#3]
They are defect.

**Comment by dmathieu** [comment]
Is that a talk about TDD?

**Comment by avernois** [comment]
Nope.
It'll be a short talk about how the words we use to talk about bugs makes us feel we are not accountable for them.
It's just about words. And professional.

**Comment by AntoineCezar** [comment]
:+1:

**Comment by enguerran** [comment]
If it's just about words, pourquoi est-ce qu'on cause en anglais ?

**Comment by dmathieu** [comment]
@avernois tu es dispo vendredi?

**Comment by avernois** [comment]
@dmathieu: yep, on peut se faire ça.

**Comment by dmathieu** [comment]
**/!\ WARNING: cette semaine, nous nous retrouverons à Tau, pas à Etincelle. /!\**
