### ISSUE TITLE
Automatisation de la chaine de production logicielle

### ISSUE THREAD

**Issue by shordeaux** [dojo-toulouse/bbl#7]
intégration continue
déploiement automatisé
tests de non régression (unitaire, recette, temps de réponse)

**Comment by batmat** [comment]
Le sujet est potentiellement très large. Je dois pouvoir faire un rex de notre forge + ce qu'on est train de changer (cf. http://www.brownbaglunch.fr/baggers.html#Baptiste_Mathus_Toulouse-jenkins-qui-pique)

**Comment by demental** [comment]
Etincelle ou tau?

**Comment by dmathieu** [comment]
Peu importe. Il n'y a pas de réservation faite encore, mais il y a de la place à Etincelle.

**Comment by batmat** [comment]
Perso, ça m'est égal, mais je veux bien visiter Tau puisque c'est déjà fait pour Etincelle ;-).
Côté sujet, vous le voyez comment : brainstorm/discussion comme pour ChatOps, ou une à plusieurs personnes pour animer (en mode discussion quand même).
Si ça intéresser, je peux proposer une version alpha des prez que je prépare pour l'[AgileTour Toulouse fin nov](http://agiletoulouse.strikingly.com/) et le [JUG mi déc](http://www.meetup.com/fr/Toulouse-Java-User-Group/events/226522097/). Tout en dérivant/zoomant en fonction des questions bien sûr.

**Comment by dmathieu** [comment]
Nous sommes totalement ouvert à une présentation, bien que en effet, nous sommes généralement plus en "freestyle" à discuter tous ensemble, sans forcément avoir qui que ce soit pour animer (il y a toujours quelqu'un qui pense à recenter si nécessaire).

**Comment by dmathieu** [comment]
Afin d'alterner, je vous propose Etincelle et nous pourrons le faire à Tau le 27 novembre.

**Comment by dmathieu** [comment]
Je ferme cette issue, vu que nous avons discuté du sujet vendredi dernier.
@shordeaux tu n'étais pas présent. N'hésite pas à relancer le sujet si tu le désire.
