### ISSUE TITLE
Back to basics : SSL

### ISSUE THREAD

**Issue by fcabestre** [dojo-toulouse/bbl#9]

**Comment by dmathieu** [comment]
@fcabestre tu aurais un vendredi ou tu pourrais venir pour que l'on fasse ce sujet?

**Comment by fcabestre** [comment]
```
Salut,

Pas avant le vendredi 9 octobre. Mais à partir de là ça sera avec
plaisir.

Fred.

Le 08/09/2015 10:54, Damien Mathieu a
  écrit :


  @fcabestre tu aurais un vendredi ou
    tu pourrais venir pour que l'on fasse ce sujet?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by dmathieu** [comment]
Cool. On peut prévoir ca pour le 16 ou le 30. Reparlons-en début octobre.

**Comment by fcabestre** [comment]
```
Ça roule

Le 08/09/2015 17:09, Damien Mathieu a
  écrit :


  Cool. On peut prévoir ca pour le 16 ou le 30. Reparlons-en
    début octobre.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by dmathieu** [comment]
@fcabestre on est fin octobre :smile:
Quand serais-tu disponible? (on a un BBL ce vendredi, puis le 13 et 27 novembre).

**Comment by fcabestre** [comment]
Si le 27 ça vous va, je préfère. Je suis décidément actuellement dans 
une zone de turbulences :)

**Comment by dmathieu** [comment]
Le 27 c'est parfait.

**Comment by dmathieu** [comment]
@fcabestre ca marche toujours pour le 27? Ca sera à Tau.

**Comment by fcabestre** [comment]
Yep

**Comment by demental** [comment]
On avait évoqué le fait que ce sujet serait assorti d'une prez, c'est bien ça? Du coup on peut balancer un peu la sauce niveau com pour faire venir plus de monde?

**Comment by fcabestre** [comment]
Moi je n'y voit pas d'inconvénient. En revanche ma prez porte bien son 
nom : Back to basics ! Je repars de très bas, c'est vu par un dev, c'est 
pas forcément pour les ops et c'est «language agnostics».

**Comment by demental** [comment]
C'est parfait amha!

**Comment by dmathieu** [comment]
C'est parfait effectivement.

**Comment by dmathieu** [comment]
Merci Frédéric. C'était parfait. :tulip:

**Comment by fcabestre** [comment]
Merci, le plaisir était pour moi aussi.
